name: Build resume document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile resume document
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
      - run: touch resume.pdf
      - uses: actions/upload-artifact@master
        with:
          name: resume.pdf
          path: resume.pdf
