name: Build resume document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile resume document
        uses: Mastoda/resume@master
        with:
          root_file: main.tex
